yiiapp/mercadobtx/backend/controllers/SupportController.php
<?php
class SupportController extends BackendController {
	public function actionIndex() {
		if (Yii::app ()->user->isGuest) {
			$this->redirect ( '/' );
		}

		$criteria = new CDbCriteria ();
		$criteria->order = 'update_time DESC';
		
		$item_count = SupportTicket::model ()->count ( $criteria );
		
		$pages = new CPagination ( $item_count );
		$pages->setPageSize ( Yii::app ()->params ['defaultListPerPage'] );
		$pages->applyLimit ( $criteria ); // the trick is here!
		
		$this->render ( 'index', array (
				'model' => SupportTicket::model ()->findAll ( $criteria ),
				'item_count' => $item_count,
				'page_size' => Yii::app ()->params ['defaultListPerPage'],
				'items_count' => $item_count,
				'pages' => $pages 
		) );
	}
	
	public function actionTicket() {
		if (Yii::app ()->user->isGuest) {
			$this->redirect ( '/' );
		}
		
		$request = Yii::app ()->request;
		$ticketid = $request->getParam ( 'id' );
		if (! $ticketid) {
			$this->redirect ( '/' );
		}
		$user = Yii::app ()->user->data ();
		$model = new UpdateTicketForm ();
		$formData = $request->getPost ( get_class ( $model ), false );
		if ($formData) {
			$model->attributes = $formData;
			if (! $model->hasErrors ()) {
				$newticket_message = new SupportTicketMessage ();
				$newticket_message->body = $model->body;
				if (! Yii::app ()->user->isGuest) {
					$newticket_message->id_ticket = $ticketid;
					$newticket_message->id_user = $user->id;
				}
				if (! $newticket_message->save ()) {
					Yii::app ()->user->setFlash ( 'error', Yii::t ( 'translation', 'Unable to create ticket' ) );
				}
				Yii::app ()->user->setFlash ( 'success', Yii::t ( 'translation', 'Ticket #{ticket_id} Updated', array (
				'{ticket_id}' => $ticketid
				) ) );
			}
		}
		
		$messages = SupportTicketMessage::model ()->findAllByAttributes ( array (
				'id_ticket' => $ticketid 
		) );
		$this->render ( 'ticket', array (
				'model' => SupportTicket::model ()->findByPk ( $ticketid ),
				'updatemodel' => $model,
				'user' => $user,
				'messages' => $messages 
		) );
	}
	
	// Uncomment the following methods and override them if needed
	/*
	 * public function filters() { // return the filter configuration for this controller, e.g.: return array( 'inlineFilterName', array( 'class'=>'path.to.FilterClass', 'propertyName'=>'propertyValue', ), ); } public function actions() { // return external action classes, e.g.: return array( 'action1'=>'path.to.ActionClass', 'action2'=>array( 'class'=>'path.to.AnotherActionClass', 'propertyName'=>'propertyValue', ), ); }
	 */
}

yiiapp/mercadobtx/frontend/controllers/SupportController.php
<?php
class SupportController extends LoginRequiredController {
	public $leftmenu = 'support';
	public function actionIndex() {
		$model = new CreateTicketForm ();
		
		$request = Yii::app ()->request;
		
		$formData = $request->getPost ( get_class ( $model ), false );
		if ($formData) {
			$model->attributes = $formData;
			if (! $model->hasErrors ()) {
				$newticket = new SupportTicket ();
				$newticket->subject = $model->subject;
				
				$newticket_message = new SupportTicketMessage ();
				$newticket_message->body = $model->body;
				if (! Yii::app ()->user->isGuest) {
					$user = Yii::app ()->user->data ();
					$newticket->id_user = $user->id;
					$newticket_message->id_user = $user->id;
				}
				if (! $newticket->save ()) {
					Yii::app ()->user->setFlash ( 'error', Yii::t ( 'translation', 'Unable to create ticket' ) );
				} else {
					$newticket_message->id_ticket = $newticket->id;
					$newticket_message->save ();
				}
				Yii::app ()->user->setFlash ( 'success', Yii::t ( 'translation', ' Ticket #{ticket_id} Created', array (
						'{ticket_id}' => $newticket->id 
				) ) );
			}
		}
		$this->render ( 'index', array (
				'model' => $model 
		) );
	}
	public function actionTickets() {
		if (Yii::app ()->user->isGuest) {
			$this->redirect ( '/' );
		}
		
		$user = Yii::app ()->user->data ();
		
		$criteria = new CDbCriteria ();
		$criteria->condition = 'id_user = :id';
		$criteria->order = 'update_time DESC';
		$criteria->params = array (
				':id' => $user->id 
		);
		
		$item_count = SupportTicket::model ()->count ( $criteria );
		
		$pages = new CPagination ( $item_count );
		$pages->setPageSize ( Yii::app ()->params ['defaultListPerPage'] );
		$pages->applyLimit ( $criteria ); // the trick is here!
		
		$this->render ( 'tickets', array (
				'model' => SupportTicket::model ()->findAll ( $criteria ),
				'item_count' => $item_count,
				'page_size' => Yii::app ()->params ['defaultListPerPage'],
				'items_count' => $item_count,
				'pages' => $pages 
		) );
	}

	public function actionTicket() {
		if (Yii::app ()->user->isGuest) {
			$this->redirect ( '/' );
		}
		
		$request = Yii::app ()->request;
		$ticketid = $request->getParam ( 'id' );
		if (! $ticketid) {
			$this->redirect ( '/' );
		}
		$user = Yii::app ()->user->data ();
		$model = new CreateTicketForm ();
		$formData = $request->getPost ( get_class ( $model ), false );
		if ($formData) {
			$model->attributes = $formData;
			if (! $model->hasErrors ()) {
				$newticket_message = new SupportTicketMessage ();
				$newticket_message->body = $model->body;
				if (! Yii::app ()->user->isGuest) {
					$newticket_message->id_ticket = $ticketid;
					$newticket_message->id_user = $user->id;
				}
				if (! $newticket_message->save ()) {
					Yii::app ()->user->setFlash ( 'error', Yii::t ( 'translation', 'Unable to create ticket' ) );
				}
				Yii::app ()->user->setFlash ( 'success', Yii::t ( 'translation', 'Ticket #{ticket_id} Updated', array (
				'{ticket_id}' => $ticketid
				) ) );
			}
		}
		

		$messages = SupportTicketMessage::model()->findAllByAttributes(array(
			'id_ticket' => $ticketid
		));
		$this->render ( 'ticket', array (
				'model' => SupportTicket::model ()->findByPk ( $ticketid ),
				'updatemodel' => $model,
				'user' => $user,
				'messages' => $messages,
		) );
	}
	// Uncomment the following methods and override them if needed
	/*
	 * public function filters() { // return the filter configuration for this controller, e.g.: return array( 'inlineFilterName', array( 'class'=>'path.to.FilterClass', 'propertyName'=>'propertyValue', ), ); } public function actions() { // return external action classes, e.g.: return array( 'action1'=>'path.to.ActionClass', 'action2'=>array( 'class'=>'path.to.AnotherActionClass', 'propertyName'=>'propertyValue', ), ); }
	 */
}

yiiapp/mercadobtx/frontend/views/support/index.php
<?php
/*
 * @var $this AccountController @var $model AccountForm
 */
$this->breadcrumbs = array (
		'Support' 
);
?>

<div class="row">
	<ul class="nav nav-tabs">
		<li class="active"><a href="#"><?php echo Yii::t('translation', 'support_top_tab_new'); ?></a></li>
		<li><a href="<?php echo $this->createUrl('support/tickets');?>"><?php echo Yii::t('translation', 'support_top_tab_open'); ?></a></li>
	</ul>
</div>
<br>
<br>
<h4 class="" style="text-transform: uppercase; font-size: 1.8em;"><?php echo Yii::t('translation', 'support_top_title'); ?></h4>
<?php

$form = $this->beginWidget ( 'yiistrap.widgets.TbActiveForm', array () );

?>

<div class="row">
	<div class="col-md-10">

		<?php echo $form->textFieldControlGroup($model, 'subject', array('class' => 'form-control', 'size' => '30')); ?>						
		<?php echo $form->textAreaControlGroup($model, 'body', array('class' => 'form-control', 'size' => '255', 'rows' => '11')); ?>
	</div>
</div>

<div class="row">
	<div class="col-md-10" style="padding-top: 2em;">
              <?php
					$this->widget ( 'bootstrap.widgets.TbButton', array (
							'buttonType' => 'submit',
							'type' => 'primary',
							'label' => Yii::t ( 'translation', 'support_button' ),
							'icon' => 'ok' 
					) );
				?>
	</div>
</div>

<?php $this->endWidget(); ?>

yiiapp/mercadobtx/frontend/views/support/ticket.php
<?php
/*
 * @var $this AccountController @var $model AccountForm
 */
$this->breadcrumbs = array (
		'Support' 
);
?>

<h4 class="" style="text-transform: uppercase; font-size: 1.8em;"><?php echo Yii::t('translation', 'ticket_top_title'); ?></h4>
<?php

$form = $this->beginWidget ( 'yiistrap.widgets.TbActiveForm', array () );

?>

<div class="row">
	<div class="col-md-2">
		<div>
			<?php echo Yii::t('translation', 'ticket_status'); ?>
		</div>
	</div>
	<div class="col-md-8">
		<div>
			<?php echo $model->status; ?>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-2">
		<div>
			<?php echo Yii::t('translation', 'ticket_subject'); ?>
		</div>
	</div>
	<div class="col-md-8">
		<div>
			<?php echo $model->subject; ?>
		</div>
	</div>
</div>

<?php foreach( $messages as $msg ):?>
<hr/>
<div class="row">
	<div class="col-md-10">
		<?php echo $msg->body; ?>
	</div>
</div>

<?php endforeach; ?>

<div class="row">
	<div class="col-md-10">
		<?php echo $form->textAreaControlGroup($updatemodel, 'body', array('class' => 'form-control', 'size' => '255', 'rows' => '11')); ?>
	</div>
</div>

<div class="row">
	<div class="col-md-10" style="padding-top: 2em;">
              <?php
					$this->widget ( 'bootstrap.widgets.TbButton', array (
							'buttonType' => 'submit',
							'type' => 'primary',
							'label' => Yii::t ( 'translation', 'ticket_button' ),
							'icon' => 'ok' 
					) );
				?>
	</div>
</div>

<?php $this->endWidget(); ?>

yiiapp/mercadobtx/frontend/views/support/tickets.php
<?php
/*
 * @var $this AccountController @var $model AccountForm
 */
$this->breadcrumbs = array (
		'Support' 
);
?>

<div class="row">
	<ul class="nav nav-tabs">
		<li><a href="/<?php echo Yii::t('translation', 'support'); ?>"><?php echo Yii::t('translation', 'support_top_tab_new'); ?></a></li>
		<li class="active"><a href="#"><?php echo Yii::t('translation', 'support_top_tab_open'); ?></a></li>
	</ul>
</div>

<?php if ( count($model) <= 0 ) :?>
<div class="alert alert-danger"><?php echo Yii::t('translation', 'no_tickets_message'); ?></div>
<?php else :?>
<div class="panel panel-default">
	<!-- Default panel contents -->
	<div class="panel-heading"><?php echo Yii::t('translation', 'tickets_new_title'); ?></div>

	<!-- Table -->
	<table class="table">
		<thead>
			<tr>
				<th><?php echo Yii::t('translation', 'tickets_field_1'); ?></th>
				<th><?php echo Yii::t('translation', 'tickets_field_2'); ?></th>
				<th><?php echo Yii::t('translation', 'tickets_field_3'); ?></th>
				<th><?php echo Yii::t('translation', 'tickets_field_4'); ?></th>

			</tr>
		</thead>
		<tbody>
			<?php foreach ( $model as $m ) :?>
				<tr>
				<td><a
					href="<?php echo $this->createUrl('support/ticket',array('id' => $m->id)); ?>"><?php echo $m->id ?><a /></td>
				<td><a
					href="<?php echo $this->createUrl('support/ticket',array('id' => $m->id)); ?>"><?php echo $m->status ?></a></td>
				<td><a
					href="<?php echo $this->createUrl('support/ticket',array('id' => $m->id)); ?>"><?php echo $m->subject ?></a></td>
				<td><a
					href="<?php echo $this->createUrl('support/ticket',array('id' => $m->id)); ?>"><?php echo $m->update_time ?></a></td>

			</tr>
			<?php endforeach; ?>
	
	
	</table>



	<div class="bs-example">

			<?php
	$data = array ();
	foreach ( $model as $m ) { // loop to get the data (this is different from the complex way)
		$data [] = $m->attributes;
	}
	
	// the pagination widget with some options to mess
	$this->widget ( 'CLinkPager', array (
			'currentPage' => $pages->getCurrentPage (),
			'itemCount' => $item_count,
			'pageSize' => $page_size,
			'maxButtonCount' => 5,
			'header' => '',
			'htmlOptions' => array (
					'class' => 'pagination' 
			),
			'firstPageLabel' => '<i class="glyphicon glyphicon-step-backward"></i>',
			'prevPageLabel' => '<i class="glyphicon glyphicon-backward"></i>',
			'nextPageLabel' => '<i class="glyphicon glyphicon-forward"></i>',
			'lastPageLabel' => '<i class="glyphicon glyphicon-step-forward"></i>' 
	) );
	
	?>
    </div>
<?php endif; ?>
</div>
</div>